language: java
jdk:
  - openjdk17

env:
  global:
    - GRADLE_OPTS="-Dorg.gradle.daemon=false"

addons:
  sonarcloud:
    organization: EvgenShaman

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

script:
  - chmod +x gradlew
  - ./gradlew clean test jacocoTestReport sonarqube \
    -Dsonar.login=$SONAR_TOKEN
    -Dsonar.organization=EvgenShaman \
    -Dsonar.host.url=https://sonarcloud.io

after_success:
  - echo "✅ Анализ кода завершён! Результаты на https://sonarcloud.io"