language: java
jdk: openjdk17  # Минимальная версия для SonarCloud Scanner

addons:
  sonarcloud:
    organization: "evgenshaman"  # Ключ организации из SonarCloud
    token: $SONAR_TOKEN                   # Зашифрованная переменная из Travis CI

script:
  # Команда для Maven: сборка, тесты и анализ SonarCloud
  - ./gradlew sonarqube -Dsonar.login=$SONAR_TOKEN -Dsonar.projectKey=$SONAR_TOKEN

